/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-19 06:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.Doctordao;
import model.Doctordata;

public final class admin_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.Doctordao");
    _jspx_imports_classes.add("model.Doctordata");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Home :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- bootstrap-css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/bootstrap.min.css\" >\r\n");
      out.write("<!-- //bootstrap-css -->\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"admin/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"admin/css/style-responsive.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<!-- font CSS -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/font.css\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"admin/css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/morris.css\" type=\"text/css\"/>\r\n");
      out.write("<!-- calendar -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/monthly.css\">\r\n");
      out.write("<!-- //calendar -->\r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<script src=\"admin/js/jquery2.0.3.min.js\"></script>\r\n");
      out.write("<script src=\"admin/js/raphael-min.js\"></script>\r\n");
      out.write("<script src=\"admin/js/morris.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

String email = null;
if(session.getAttribute("data")!=null){
	email = (String)session.getAttribute("data");
}
else{
	response.sendRedirect("admin-login.jsp");
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("<!--header start-->\r\n");
      out.write("<header class=\"header fixed-top clearfix\">\r\n");
      out.write("<!--logo start-->\r\n");
      out.write("<div class=\"brand\">\r\n");
      out.write("    <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("        VISITORS\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"sidebar-toggle-box\">\r\n");
      out.write("        <div class=\"fa fa-bars\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--logo end-->\r\n");
      out.write("<div class=\"nav notify-row\" id=\"top_menu\">\r\n");
      out.write("    <!--  notification start -->\r\n");
      out.write("    <ul class=\"nav top-menu\">\r\n");
      out.write("        <!-- settings start -->\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("                <span class=\"badge bg-success\">8</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended tasks-bar\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p class=\"\">You have 8 pending tasks</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Target Sell</h5>\r\n");
      out.write("                                <p>25% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"45\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Product Delivery</h5>\r\n");
      out.write("                                <p>45% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"78\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Payment collection</h5>\r\n");
      out.write("                                <p>87% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"60\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Target Sell</h5>\r\n");
      out.write("                                <p>33% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"90\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"external\">\r\n");
      out.write("                    <a href=\"#\">See All Tasks</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- settings end -->\r\n");
      out.write("        <!-- inbox dropdown start-->\r\n");
      out.write("        <li id=\"header_inbox_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                <span class=\"badge bg-important\">4</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended inbox\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p class=\"red\">You have 4 Mails</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Jonathan Smith</span>\r\n");
      out.write("                                <span class=\"time\">Just now</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Hello, this is an example msg.\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/1.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Jane Doe</span>\r\n");
      out.write("                                <span class=\"time\">2 min ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Nice admin template\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Tasi sam</span>\r\n");
      out.write("                                <span class=\"time\">2 days ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    This is an example msg.\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/2.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Mr. Perfect</span>\r\n");
      out.write("                                <span class=\"time\">2 hour ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Hi there, its a test\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">See all messages</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- inbox dropdown end -->\r\n");
      out.write("        <!-- notification dropdown start-->\r\n");
      out.write("        <li id=\"header_notification_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("                <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                <span class=\"badge bg-warning\">3</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended notification\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p>Notifications</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-info clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #1 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-danger clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #2 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-success clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #3 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- notification dropdown end -->\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!--  notification end -->\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top-nav clearfix\">\r\n");
      out.write("    <!--search & user info start-->\r\n");
      out.write("    <ul class=\"nav pull-right top-menu\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <input type=\"text\" class=\"form-control search\" placeholder=\" Search\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- user login dropdown start-->\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <img alt=\"\" src=\"images/2.png\">\r\n");
      out.write("                <span class=\"username\">");
out.print(email); 
      out.write("</span>\r\n");
      out.write("                <b class=\"caret\"></b>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended logout\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\" fa fa-suitcase\"></i>Profile</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-cog\"></i> Settings</a></li>\r\n");
      out.write("                <li><a href=\"login.html\"><i class=\"fa fa-key\"></i> Log Out</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- user login dropdown end -->\r\n");
      out.write("       \r\n");
      out.write("    </ul>\r\n");
      out.write("    <!--search & user info end-->\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--header end-->\r\n");
      out.write("<!--sidebar start-->\r\n");
      out.write("<aside>\r\n");
      out.write("    <div id=\"sidebar\" class=\"nav-collapse\">\r\n");
      out.write("        <!-- sidebar menu start-->\r\n");
      out.write("        <div class=\"leftside-navigation\">\r\n");
      out.write("            <ul class=\"sidebar-menu\" id=\"nav-accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"active\" href=\"admin-home.jsp\">\r\n");
      out.write("                        <span>Dashboard</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"sub-menu\">\r\n");
      out.write("                    <a href=\"admin-doctor_list.jsp\">\r\n");
      out.write("                        <span>Doctor</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"admin_patient_list.jsp\">\r\n");
      out.write("                        <span>Patient</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"sub-menu\">\r\n");
      out.write("                    <a href=\"all-payments.jsp\">\r\n");
      out.write("                        <span>Payments</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \r\n");
      out.write("            </ul>            </div>\r\n");
      out.write("        <!-- sidebar menu end-->\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("<!--sidebar end-->\r\n");
      out.write("<!--main content start-->\r\n");
      out.write("<section id=\"main-content\">\r\n");
      out.write("	<section class=\"wrapper\">\r\n");
      out.write("		<div class=\"form-w3layouts\">\r\n");
      out.write("            <!-- page start-->\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <section class=\"panel\">\r\n");
      out.write("                        <header class=\"panel-heading\">\r\n");
      out.write("                            Form validations\r\n");
      out.write("                            <span class=\"tools pull-right\">\r\n");
      out.write("                                <a class=\"fa fa-chevron-down\" href=\"javascript:;\"></a>\r\n");
      out.write("                                <a class=\"fa fa-cog\" href=\"javascript:;\"></a>\r\n");
      out.write("                                <a class=\"fa fa-times\" href=\"javascript:;\"></a>\r\n");
      out.write("                             </span>\r\n");
      out.write("                        </header>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <div class=\" form\">\r\n");
      out.write("                         \r\n");
      out.write("                             ");
int did=Integer.parseInt(request.getParameter("did")); 
      out.write("\r\n");
      out.write("                             \r\n");
      out.write("                            ");
Doctordata d = Doctordao.getDoctorByiD(did); 
      out.write("\r\n");
      out.write("                                <form class=\"cmxform form-horizontal \" id=\"commentForm\" method=\"post\" action=\"DoctorController\" novalidate=\"novalidate\">\r\n");
      out.write("                                    <div class=\"form-group \">\r\n");
      out.write("                                        <!-- <label for=\"cname\" class=\"control-label col-lg-3\">Id</label> -->\r\n");
      out.write("                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                            <input type=\"hidden\" class=\"form-control\"  name=\"did\"   value=\"");
      out.print(d.getDid());
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group \">\r\n");
      out.write("                                        <label for=\"cname\" class=\"control-label col-lg-3\">Name</label>\r\n");
      out.write("                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                            <input class=\" form-control\"  name=\"dname\" type=\"text\" value=\"");
      out.print(d.getDname());
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group \">\r\n");
      out.write("                                        <label for=\"cemail\" class=\"control-label col-lg-3\">Contact</label>\r\n");
      out.write("                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                            <input class=\"form-control \"  type=\"text\" name=\"dcontact\" value=\"");
      out.print(d.getDContact());
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                     <div class=\"form-group \">\r\n");
      out.write("                                        <label for=\"cemail\" class=\"control-label col-lg-3\">Address</label>\r\n");
      out.write("                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                            <input class=\"form-control \"  type=\"text\" name=\"dcaddress\" value=\"");
      out.print(d.getDcaddress());
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group \">\r\n");
      out.write("                                        <label for=\"curl\" class=\"control-label col-lg-3\">Email</label>\r\n");
      out.write("                                        <div class=\"col-lg-6\">\r\n");
      out.write("                                            <input class=\"form-control \"  type=\"email\" name=\"demail\" value=\"");
      out.print(d.getDemail());
      out.write("\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <div class=\"col-lg-offset-3 col-lg-6\">\r\n");
      out.write("                                            <button class=\"btn btn-primary\" type=\"submit\" name=\"action\" value=\"aupdate\">Update</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("          \r\n");
      out.write("            <!-- page end-->\r\n");
      out.write("        </div>\r\n");
      out.write("</section>\r\n");
      out.write(" <!-- footer -->\r\n");
      out.write("		  <div class=\"footer\">\r\n");
      out.write("			<div class=\"wthree-copyright\">\r\n");
      out.write("			  <p>© 2017 Visitors. All rights reserved | Design by <a href=\"http://w3layouts.com\">W3layouts</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("		  </div>\r\n");
      out.write("  <!-- / footer -->\r\n");
      out.write("</section>\r\n");
      out.write("<!--main content end-->\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"admin/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.dcjqaccordion.2.7.js\"></script>\r\n");
      out.write("<script src=\"admin/js/scripts.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.slimscroll.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.nicescroll.js\"></script>\r\n");
      out.write("<!--[if lte IE 8]><script language=\"javascript\" type=\"text/javascript\" src=\"js/flot-chart/excanvas.min.js\"></script><![endif]-->\r\n");
      out.write("<script src=\"admin/js/jquery.scrollTo.js\"></script>\r\n");
      out.write("<!-- morris JavaScript -->	\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		//BOX BUTTON SHOW AND CLOSE\r\n");
      out.write("	   jQuery('.small-graph-box').hover(function() {\r\n");
      out.write("		  jQuery(this).find('.box-button').fadeIn('fast');\r\n");
      out.write("	   }, function() {\r\n");
      out.write("		  jQuery(this).find('.box-button').fadeOut('fast');\r\n");
      out.write("	   });\r\n");
      out.write("	   jQuery('.small-graph-box .box-close').click(function() {\r\n");
      out.write("		  jQuery(this).closest('.small-graph-box').fadeOut(200);\r\n");
      out.write("		  return false;\r\n");
      out.write("	   });\r\n");
      out.write("	   \r\n");
      out.write("	    //CHARTS\r\n");
      out.write("	    function gd(year, day, month) {\r\n");
      out.write("			return new Date(year, month - 1, day).getTime();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		graphArea2 = Morris.Area({\r\n");
      out.write("			element: 'hero-area',\r\n");
      out.write("			padding: 10,\r\n");
      out.write("        behaveLikeLine: true,\r\n");
      out.write("        gridEnabled: false,\r\n");
      out.write("        gridLineColor: '#dddddd',\r\n");
      out.write("        axes: true,\r\n");
      out.write("        resize: true,\r\n");
      out.write("        smooth:true,\r\n");
      out.write("        pointSize: 0,\r\n");
      out.write("        lineWidth: 0,\r\n");
      out.write("        fillOpacity:0.85,\r\n");
      out.write("			data: [\r\n");
      out.write("				{period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649},\r\n");
      out.write("				{period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051},\r\n");
      out.write("				{period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910},\r\n");
      out.write("				{period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695},\r\n");
      out.write("				{period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300},\r\n");
      out.write("				{period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891},\r\n");
      out.write("				{period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598},\r\n");
      out.write("				{period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185},\r\n");
      out.write("				{period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038},\r\n");
      out.write("			\r\n");
      out.write("			],\r\n");
      out.write("			lineColors:['#eb6f6f','#926383','#eb6f6f'],\r\n");
      out.write("			xkey: 'period',\r\n");
      out.write("            redraw: true,\r\n");
      out.write("            ykeys: ['iphone', 'ipad', 'itouch'],\r\n");
      out.write("            labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],\r\n");
      out.write("			pointSize: 2,\r\n");
      out.write("			hideHover: 'auto',\r\n");
      out.write("			resize: true\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	   \r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("<!-- calendar -->\r\n");
      out.write("	<script type=\"text/javascript\" src=\"admin/js/monthly.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(window).load( function() {\r\n");
      out.write("\r\n");
      out.write("			$('#mycalendar').monthly({\r\n");
      out.write("				mode: 'event',\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			$('#mycalendar2').monthly({\r\n");
      out.write("				mode: 'picker',\r\n");
      out.write("				target: '#mytarget',\r\n");
      out.write("				setWidth: '250px',\r\n");
      out.write("				startHidden: true,\r\n");
      out.write("				showTrigger: '#mytarget',\r\n");
      out.write("				stylePast: true,\r\n");
      out.write("				disablePast: true\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("		switch(window.location.protocol) {\r\n");
      out.write("		case 'http:':\r\n");
      out.write("		case 'https:':\r\n");
      out.write("		// running on a server, should be good.\r\n");
      out.write("		break;\r\n");
      out.write("		case 'file:':\r\n");
      out.write("		alert('Just a heads-up, events will not work when run locally.');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- //calendar -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
