/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-07 06:32:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.Patientdao;
import model.Patientdata;
import java.util.List;

public final class admin_005fpatient_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.Patientdao");
    _jspx_imports_classes.add("model.Patientdata");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--A Design by W3layouts\r\n");
      out.write("Author: W3layout\r\n");
      out.write("Author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Responsive_table :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- bootstrap-css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/bootstrap.min.css\" >\r\n");
      out.write("<!-- //bootstrap-css -->\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"admin/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"admin/css/style-responsive.css\" rel=\"stylesheet\"/>\r\n");
      out.write("<!-- font CSS -->\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"admin/css/font.css\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"admin/css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<script src=\"admin/js/jquery2.0.3.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section id=\"container\">\r\n");
      out.write("<!--header start-->\r\n");
      out.write("<header class=\"header fixed-top clearfix\">\r\n");
      out.write("<!--logo start-->\r\n");
      out.write("<div class=\"brand\">\r\n");
      out.write("\r\n");
      out.write("    <a href=\"index.html\" class=\"logo\">\r\n");
      out.write("        VISITORS\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"sidebar-toggle-box\">\r\n");
      out.write("        <div class=\"fa fa-bars\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--logo end-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav notify-row\" id=\"top_menu\">\r\n");
      out.write("    <!--  notification start -->\r\n");
      out.write("    <ul class=\"nav top-menu\">\r\n");
      out.write("        <!-- settings start -->\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("                <span class=\"badge bg-success\">8</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended tasks-bar\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p class=\"\">You have 8 pending tasks</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Target Sell</h5>\r\n");
      out.write("                                <p>25% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"45\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Product Delivery</h5>\r\n");
      out.write("                                <p>45% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"78\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Payment collection</h5>\r\n");
      out.write("                                <p>87% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"60\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <div class=\"task-info clearfix\">\r\n");
      out.write("                            <div class=\"desc pull-left\">\r\n");
      out.write("                                <h5>Target Sell</h5>\r\n");
      out.write("                                <p>33% , Deadline  12 June’13</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                    <span class=\"notification-pie-chart pull-right\" data-percent=\"90\">\r\n");
      out.write("                            <span class=\"percent\"></span>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"external\">\r\n");
      out.write("                    <a href=\"#\">See All Tasks</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- settings end -->\r\n");
      out.write("        <!-- inbox dropdown start-->\r\n");
      out.write("        <li id=\"header_inbox_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <i class=\"fa fa-envelope-o\"></i>\r\n");
      out.write("                <span class=\"badge bg-important\">4</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended inbox\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p class=\"red\">You have 4 Mails</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Jonathan Smith</span>\r\n");
      out.write("                                <span class=\"time\">Just now</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Hello, this is an example msg.\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/1.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Jane Doe</span>\r\n");
      out.write("                                <span class=\"time\">2 min ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Nice admin template\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/3.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Tasi sam</span>\r\n");
      out.write("                                <span class=\"time\">2 days ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    This is an example msg.\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <span class=\"photo\"><img alt=\"avatar\" src=\"images/2.png\"></span>\r\n");
      out.write("                                <span class=\"subject\">\r\n");
      out.write("                                <span class=\"from\">Mr. Perfect</span>\r\n");
      out.write("                                <span class=\"time\">2 hour ago</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"message\">\r\n");
      out.write("                                    Hi there, its a test\r\n");
      out.write("                                </span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">See all messages</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- inbox dropdown end -->\r\n");
      out.write("        <!-- notification dropdown start-->\r\n");
      out.write("        <li id=\"header_notification_bar\" class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("                <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("                <span class=\"badge bg-warning\">3</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended notification\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <p>Notifications</p>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-info clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #1 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-danger clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #2 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"alert alert-success clearfix\">\r\n");
      out.write("                        <span class=\"alert-icon\"><i class=\"fa fa-bolt\"></i></span>\r\n");
      out.write("                        <div class=\"noti-info\">\r\n");
      out.write("                            <a href=\"#\"> Server #3 overloaded.</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- notification dropdown end -->\r\n");
      out.write("    </ul>\r\n");
      out.write("    <!--  notification end -->\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"top-nav clearfix\">\r\n");
      out.write("    <!--search & user info start-->\r\n");
      out.write("    <ul class=\"nav pull-right top-menu\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <input type=\"text\" class=\"form-control search\" placeholder=\" Search\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- user login dropdown start-->\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("            <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\">\r\n");
      out.write("                <img alt=\"\" src=\"images/2.png\">\r\n");
      out.write("                <span class=\"username\">John Doe</span>\r\n");
      out.write("                <b class=\"caret\"></b>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu extended logout\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\" fa fa-suitcase\"></i>Profile</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-cog\"></i> Settings</a></li>\r\n");
      out.write("                <li><a href=\"login.html\"><i class=\"fa fa-key\"></i> Log Out</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- user login dropdown end -->\r\n");
      out.write("       \r\n");
      out.write("    </ul>\r\n");
      out.write("    <!--search & user info end-->\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--header end-->\r\n");
      out.write("<!--sidebar start-->\r\n");
      out.write("<aside>\r\n");
      out.write("    <div id=\"sidebar\" class=\"nav-collapse\">\r\n");
      out.write("        <!-- sidebar menu start-->\r\n");
      out.write("        <div class=\"leftside-navigation\">\r\n");
      out.write("            <ul class=\"sidebar-menu\" id=\"nav-accordion\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a class=\"active\" href=\"admin-home.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-dashboard\"></i>\r\n");
      out.write("                        <span>Dashboard</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"sub-menu\">\r\n");
      out.write("                    <a href=\"admin-seller-list.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-book\"></i>\r\n");
      out.write("                        <span>Sellers</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"admin-customer-list.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-bullhorn\"></i>\r\n");
      out.write("                        <span>Customers</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"sub-menu\">\r\n");
      out.write("                    <a href=\"admin-product-list.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-th\"></i>\r\n");
      out.write("                        <span>Products</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"sub-menu\">\r\n");
      out.write("                    <a href=\"all-payments.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("                        <span>Payments</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \r\n");
      out.write("            </ul>            </div>\r\n");
      out.write("        <!-- sidebar menu end-->\r\n");
      out.write("    </div>\r\n");
      out.write("</aside>\r\n");
      out.write("<!--sidebar end-->\r\n");
      out.write("<!--main content start-->\r\n");
      out.write("<section id=\"main-content\">\r\n");
      out.write("	<section class=\"wrapper\">\r\n");
      out.write("		<div class=\"table-agile-info\">\r\n");
      out.write(" <div class=\"panel panel-default\">\r\n");
      out.write("    <div class=\"panel-heading\">\r\n");
      out.write("     Basic table\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <table class=\"table\" ui-jq=\"footable\" ui-options='{\r\n");
      out.write("        \"paging\": {\r\n");
      out.write("          \"enabled\": true\r\n");
      out.write("        },\r\n");
      out.write("        \"filtering\": {\r\n");
      out.write("          \"enabled\": true\r\n");
      out.write("        },\r\n");
      out.write("        \"sorting\": {\r\n");
      out.write("          \"enabled\": true\r\n");
      out.write("        }}'>\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th data-breakpoints=\"xs\">ID</th>\r\n");
      out.write("            <th>Name</th>\r\n");
      out.write("            <th>Contact</th>\r\n");
      out.write("            <th data-breakpoints=\"xs\">Address</th>\r\n");
      out.write("           \r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("         ");
List<Patientdata> list=Patientdao.getallpatient();  
      out.write("\r\n");
      out.write("		");
for(Patientdata p:list){ 
      out.write(" \r\n");
      out.write("          <tr data-expanded=\"true\">\r\n");
      out.write("            <td>");
      out.print(p.getId() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(p.getName() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(p.getContact() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(p.getAddress() );
      out.write("</td>\r\n");
      out.write("            \r\n");
      out.write("         </tr>\r\n");
      out.write("          \r\n");
      out.write("          ");
} 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write(" <!-- footer -->\r\n");
      out.write("		  <div class=\"footer\">\r\n");
      out.write("			<div class=\"wthree-copyright\">\r\n");
      out.write("			  <p>© 2017 Visitors. All rights reserved | Design by <a href=\"http://w3layouts.com\">W3layouts</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("		  </div>\r\n");
      out.write("  <!-- / footer -->\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!--main content end-->\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"admin/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.dcjqaccordion.2.7.js\"></script>\r\n");
      out.write("<script src=\"admin/js/scripts.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.slimscroll.js\"></script>\r\n");
      out.write("<script src=\"admin/js/jquery.nicescroll.js\"></script>\r\n");
      out.write("<!--[if lte IE 8]><script language=\"javascript\" type=\"text/javascript\" src=\"js/flot-chart/excanvas.min.js\"></script><![endif]-->\r\n");
      out.write("<script src=\"admin/js/jquery.scrollTo.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
