/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-13 05:09:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Doctordata;
import model.Appointmentdata;

public final class Show_005fappointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Appointmentdata");
    _jspx_imports_classes.add("model.Doctordata");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Appointment recipe</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Health Plus Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free web designs for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("		function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-meta-tags-->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/wickedpicker.css\" rel=\"stylesheet\" type='text/css' media=\"all\" />\r\n");
      out.write("			<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<!-- //font-awesome icons -->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Raleway:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

Appointmentdata a  = null;
   if(session.getAttribute("data")!=null){
	   a = (Appointmentdata)session.getAttribute("data");
   }
   else{
	   response.sendRedirect("appointment.jsp");
   }
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"banner-bottom\" id=\"about\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("					<h2 class=\"w3_heade_tittle_agile\">Appointment</h2>\r\n");
      out.write("			        <p class=\"sub_t_agileits\">Receipt</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"book-appointment\">\r\n");
      out.write("						<h4>Appointment Details</h4>\r\n");
      out.write("								<form action=\"AppointmentController\" method=\"post\" >\r\n");
      out.write("								<div class=\"left-agileits-w3layouts same\">\r\n");
      out.write("								<div class=\"gaps\">\r\n");
      out.write("								 <div class=\"form-group contact-forms\">\r\n");
      out.write("                                      <input type=\"hidden\" class=\"form-control\" placeholder=\"\" name=\"Appointment_id\" value=\"");
      out.print(a.getAppointment_id());
      out.write("\">\r\n");
      out.write("                                </div>\r\n");
      out.write("									<p>Patient Name</p>\r\n");
      out.write("										<input type=\"text\" name=\"Appointment_name\" placeholder=\"\" required=\"\" value=\"");
      out.print(a.getAppointment_name());
      out.write("\">\r\n");
      out.write("								</div>	\r\n");
      out.write("									<div class=\"gaps\">	\r\n");
      out.write("									<p>Phone Number</p>\r\n");
      out.write("										<input type=\"text\" name=\"Appointment_number\" placeholder=\"\" required=\"\"  value=");
      out.print(a.getAppointment_number() );
      out.write(">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"gaps\">\r\n");
      out.write("									<p>Email</p>\r\n");
      out.write("											<input type=\"email\" name=\"Appointment_email\" placeholder=\"\" required=\"\" value=\"");
      out.print(a.getAppointment_email());
      out.write("\"/>\r\n");
      out.write("									</div>	\r\n");
      out.write("									<div class=\"gaps\">\r\n");
      out.write("									<p>Symptoms</p>\r\n");
      out.write("											<input type=\"text\" name=\"Appointment_symptoms\" placeholder=\"\" required=\"\" value=\"");
      out.print(a.getAppointment_symptoms());
      out.write("\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"right-agileinfo same\">\r\n");
      out.write("								<div class=\"gaps\">\r\n");
      out.write("									<p>Select Date</p>		\r\n");
      out.write("											<input  id=\"datepicker1\" name=\"Appointment_date\" type=\"text\" value=\"");
      out.print(a.getAppointment_date());
      out.write(" %>\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'mm/dd/yyyy';}\" required=\"\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"gaps\"  >\r\n");
      out.write("									<p>Department</p>	\r\n");
      out.write("										<select class=\"option\" name=\"Appointment_department\" value=\"");
      out.print(a.getAppointment_department());
      out.write("\">\r\n");
      out.write("											<option>");
      out.print(a.getAppointment_department());
      out.write("</option>\r\n");
      out.write("											<option>Cardiology</option>\r\n");
      out.write("											<option>Ophthalmology</option>\r\n");
      out.write("											<option>Neurology</option>\r\n");
      out.write("											<option>Psychology</option>\r\n");
      out.write("											<option>Dermatology</option>\r\n");
      out.write("										</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"gaps\">\r\n");
      out.write("									<p>Gender</p>	\r\n");
      out.write("										<select class=\"option\" name=\"Appointment_gender\" value=\"");
      out.print(a.getAppointment_gender());
      out.write("\">\r\n");
      out.write("											<option>");
      out.print(a.getAppointment_gender());
      out.write("</option>\r\n");
      out.write("											<option>Male</option>\r\n");
      out.write("											<option>Female</option>\r\n");
      out.write("										</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"gaps\">\r\n");
      out.write("									<p>Time</p>		\r\n");
      out.write("										<input type=\"text\" id=\"timepicker\" name=\"Appointment_time\" class=\"timepicker option\" value=\"");
      out.print(a.getAppointment_time());
      out.write("\">	\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"clearfix\"></div>\r\n");
      out.write("                          <button type=\"submit\" name=\"action\" value=\"update\"  class=\"btn btn-block sent-butnn\">Update</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("					   </div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- icons -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
