/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-01 12:06:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewdepartment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Photo Slider with Text Fields</title>\r\n");
      out.write("  <!-- Include Swiper library CSS file -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\" />\r\n");
      out.write("  <style>\r\n");
      out.write("    /* Set height of photo slider to fill available space */\r\n");
      out.write("    .photo-slider {\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("    /* Set height of text fields to match height of photo slider */\r\n");
      out.write("    .text-fields {\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    /* Style for text field labels */\r\n");
      out.write("    label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    /* Style for text field inputs */\r\n");
      out.write("    input[type=text] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px 20px;\r\n");
      out.write("      margin: 8px 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      border: 2px solid #ccc;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      background-color: #f8f8f8;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    /* Style for submit button */\r\n");
      out.write("    input[type=submit] {\r\n");
      out.write("      background-color: #4CAF50;\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 12px 20px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- Photo slider on left side -->\r\n");
      out.write("  <div class=\"photo-slider\">\r\n");
      out.write("    <div class=\"swiper-container\">\r\n");
      out.write("      <div class=\"swiper-wrapper\">\r\n");
      out.write("        <div class=\"swiper-slide\"><img src=\"https://picsum.photos/id/1015/800/600\"></div>\r\n");
      out.write("        <div class=\"swiper-slide\"><img src=\"https://picsum.photos/id/1016/800/600\"></div>\r\n");
      out.write("        <div class=\"swiper-slide\"><img src=\"https://picsum.photos/id/1018/800/600\"></div>\r\n");
      out.write("        <div class=\"swiper-slide\"><img src=\"https://picsum.photos/id/1020/800/600\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"swiper-pagination\"></div>\r\n");
      out.write("      <div class=\"swiper-button-next\"></div>\r\n");
      out.write("      <div class=\"swiper-button-prev\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Text fields on right side -->\r\n");
      out.write("  <div class=\"text-fields\">\r\n");
      out.write("    <form>\r\n");
      out.write("      <label for=\"name\">Name:</label>\r\n");
      out.write("      <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Enter your name\">\r\n");
      out.write("      \r\n");
      out.write("      <label for=\"email\">Email:</label>\r\n");
      out.write("      <input type=\"text\" id=\"email\" name=\"email\" placeholder=\"Enter your email address\">\r\n");
      out.write("      \r\n");
      out.write("      <label for=\"message\">Message:</label>\r\n");
      out.write("      <textarea id=\"message\" name=\"message\" rows=\"6\" placeholder=\"Enter your message\"></textarea>\r\n");
      out.write("      \r\n");
      out.write("      <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Include Swiper library JavaScript file -->\r\n");
      out.write("  <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    // Initialize Swiper library\r\n");
      out.write("    var swiper = new Swiper('.swiper-container', {\r\n");
      out.write("      // Configure swiper to enable horizontal slide movement\r\n");
      out.write("      direction: 'horizontal',\r\n");
      out.write("      // Enable automatic slide movement\r\n");
      out.write("      autoplay: {\r\n");
      out.write("        delay: 5000,\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
